### ISSUE TITLE
Installation package error

### ISSUE THREAD

**Issue by martwerlen** [taye/interact.js#223]
Hi,

I just began using Meteor and I really had like to use interact.js. I added the package into my app with npm, but i obtain an error when I run the app : 
<quote>
/Users/me/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
						throw(ex);
						      ^
ReferenceError: window is not defined
    at Object.<anonymous> (/Users/me/Meteor/Colibry/.meteor/local/isopacks/npm-container/npm/node_modules/interact.js/interact.js:5831:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.Npm.require (/Users/me/Meteor/Colibry/.meteor/local/build/programs/server/boot.js:142:18)
    at Object.Meteor.npmRequire (packages/npm-container/index.js:2:1)
    at app/colibry.js:118:26
Exited with code: 8
Your application is crashing. Waiting for file change.
</quote>

I search everywhere but i can't find the solution. Could you please help me ?

THank you very much,

Martin

**Comment by taye** [comment]
Try using the `"master"` version of interact.js.

**Comment by martwerlen** [comment]
It seems to work. Thank you very much. 
Now there is no such error. But I can't succeed in having drag & drop. I'll find.

THanks you very much.
Martin

**Comment by taye** [comment]
Hi Martin,
Did you get this sorted out?
