### ISSUE TITLE
exception is thrown randomly when drag around

### ISSUE THREAD

**Issue by naivefun** [taye/interact.js#450]
```
polyfills.bundle.js:15258 Uncaught TypeError: Cannot read property 'right' of undefined
    at Interactable.dropCheck (http://localhost:3000/assets/js/debug.js:4157:79)
    at Interaction.getDrop (http://localhost:3000/assets/js/debug.js:2497:41)
    at Interaction.dragMove (http://localhost:3000/assets/js/debug.js:1968:29)
    at Interaction.pointerMove (http://localhost:3000/assets/js/debug.js:1926:75)
    at HTMLDocument.<anonymous> (http://localhost:3000/assets/js/debug.js:3348:36)
    at ZoneDelegate.invokeTask (http://localhost:3000/polyfills.bundle.js:15365:35)
    at Zone.runTask (http://localhost:3000/polyfills.bundle.js:15254:47)
    at HTMLDocument.ZoneTask.invoke (http://localhost:3000/polyfills.bundle.js:15435:33)
```

Seems caused by this
```
            if (isNumber(dropOverlap)) {
                var overlapArea  = (Math.max(0, Math.min(rect.right , dragRect.right ) - Math.max(rect.left, dragRect.left))
                    * Math.max(0, Math.min(rect.bottom, dragRect.bottom) - Math.max(rect.top , dragRect.top ))),
                    overlapRatio = overlapArea / (dragRect.width * dragRect.height);

                dropped = overlapRatio >= dropOverlap;
            }
```

the `var dragRect = draggable.getRect(draggableElement);` is returning null.

I cannot confirm what is causing this, any ideas? Thanks.

**Comment by taye** [comment]
That most likely means that an element was removed from the DOM or had `display: none` so it didn't have dimensions. I've added a check to avoid that error. I hope to make a new build with this fix in the `unstable` branch soon.

**Comment by naivefun** [comment]
yes, it's the delayed DOM update issue by NG2.
Need manually force update DOM tree to avoid this.
