### ISSUE TITLE
Can't install @next with yarn.

### ISSUE THREAD

**Issue by mathieutu** [taye/interact.js#648]
When trying to install with yarn, the url of registry seems to be wrong..
I'm sending an issue to yarn too.
```
Arguments: 
  /usr/local/bin/node /usr/local/Cellar/yarn/1.7.0/libexec/bin/yarn.js add interactjs@next

Yarn version: 
  1.7.0

Node version: 
  8.11.3

Platform: 
  darwin x64

Trace: 
  Error: https://registry.yarnpkg.com/repeat-interactable/-/repeat-interactable-1.1.2.tgz: Request failed "404 Not Found"
      at ResponseError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:218:66)
      at new ResponseError (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:324:124)
      at Request.<anonymous> (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:62463:26)
      at emitOne (events.js:116:13)
      at Request.emit (events.js:211:7)
      at Request.module.exports.Request.onRequestResponse (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:135561:10)
      at emitOne (events.js:116:13)
      at ClientRequest.emit (events.js:211:7)
      at HTTPParser.parserOnIncomingClient (_http_client.js:543:21)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:112:17)
```

**Comment by mathieutu** [comment]
Nevermind, this has no link with interactjs, and a yarn upgrade solved the issue.. 🤷‍♂️
